name: Command Line Demo

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag name of @midscene/cli'
        required: true
        default: 'latest'
      output_folder:
        description: 'Midscene report directory'
        required: true
        default: 'command-line/midscene_run/report/'
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script
        env:
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MIDSCENE_DEBUG_AI_PROFILE: 1
        run: |
          npm i -g @midscene/cli@${{ github.event.inputs.tag }}
          cd command-line
          echo "Run sauce-demo.sh"
          ./sauce-demo.sh
          echo "Run extract-github-status.sh"
          ./extract-github-status.sh
          echo "Run local-static-server.sh"
          ./local-static-server.sh

      - name: List directory contents
        run: ls -R ${{ github.workspace }}

      - name: Upload output folder
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: Midscene Report 
          path: ${{ github.workspace }}/${{ github.event.inputs.output_folder }}
